# Generated by Django 2.1.2 on 2018-10-13 21:24

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_id', models.IntegerField()),
                ('screen_name', models.CharField(max_length=10)),
                ('row', models.CharField(max_length=10)),
                ('number_of_seats', models.IntegerField()),
                ('seats_structure', models.CharField(default='-1,-1,-1,-1,-1,-1,-1,-1,-1,-1', max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
            ],
        ),
    ]
