# Generated by Django 2.1.2 on 2018-10-13 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screens',
            name='screen_id',
        ),
    ]
