# Generated by Django 2.1.2 on 2018-10-13 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0002_remove_screens_screen_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screens',
            old_name='row',
            new_name='rows',
        ),
    ]
